export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE';

export const TOGGLE_CYCLE_HIRE_VIEW = 'TOGGLE_CYCLE_HIRE_VIEW';
export const FETCH_BIKES_REQUEST = 'FETCH_BIKES_REQUEST';
export const FETCH_BIKES_SUCCESS = 'FETCH_BIKES_SUCCESS';
export const FETCH_BIKES_FAILURE = 'FETCH_BIKES_FAILURE';
export const SET_BIKES_DATA = 'SET_BIKES_DATA';